sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile .

language: generic 
script:
  - docker run -e CI=true docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-webapp"
  env: "DockerWebapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-924091992100"
  bucket_path: "docker-webapp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
